steps:
  - timeout: 600s
  - name: gcr.io/cloud-builders/docker
    args: [
      'build',
      '-f',
      './api-gateway/Dockerfile',
      '-t',
      'gcr.io/slack-api-gateway/slack-api-gateway-dev:$BUILD_ID',
      '.'
    ]
  - name: gcr.io/cloud-builders/docker
    args: [
      'push',
      'gcr.io/slack-api-gateway/slack-api-gateway-dev:$BUILD_ID'
    ]
  - name: gcr.io/cloud-builders/kubectl
    args: [
      'set',
      'image',
      'deployment/api-gateway-depl',
      'd3bug3r/slack-api-gateway=gcr.io/slack-api-gateway/slack-api-gateway-dev:$BUILD_ID',
    ]
  - name: 'gcr.io/cloud-builders/kubectl'
    id: Deploy
    args: [
      'apply',
      '-f',
      'infra/k8s/api-gateway-depl.yaml'
    ]
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
      - 'CLOUDSDK_CONTAINER_CLUSTER=slack'