steps:
  - name: gcr.io/cloud-builders/docker
    args: [
      'build',
      '-f',
      './channel/Dockerfile.dev',
      '-t',
      'gcr.io/ticketing-dev-281211/slack-channel-dev:$BUILD_ID',
      './channel'
    ]
  - name: gcr.io/cloud-builders/docker
    args: [
      'push',
      'gcr.io/ticketing-dev-281211/slack-channel-dev:$BUILD_ID'
    ]
  - name: gcr.io/cloud-builders/kubectl
    args: [
      'set',
      'image',
      'deployment/channel-depl',
      'slack-channel-dev=gcr.io/ticketing-dev-281211/slack-channel-dev:$BUILD_ID',
      '--namespace',
      'development'
    ]
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
      - 'CLOUDSDK_CONTAINER_CLUSTER=slack'