steps:
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
    dir: 'client'
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build:dev']
    dir: 'client'
  - name: 'gcr.io/cloud-builders/firebase'
    args: [
      'deploy',
      '--only=hosting'
    ]
    dir: 'client'