steps:
  - name: gcr.io/cloud-builders/docker
    args: [
      'build',
      '-f',
      './organization/Dockerfile.dev',
      '-t',
      'gcr.io/ticketing-dev-281211/slack-organization-dev:$BUILD_ID',
      './organization'
    ]
  - name: gcr.io/cloud-builders/docker
    args: [
      'push',
      'gcr.io/ticketing-dev-281211/slack-organization-dev:$BUILD_ID'
    ]
  - name: gcr.io/cloud-builders/kubectl
    args: [
      'set',
      'image',
      'deployment/organization-depl',
      'slack-organization-dev=gcr.io/ticketing-dev-281211/slack-organization-dev:$BUILD_ID',
    ]
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
      - 'CLOUDSDK_CONTAINER_CLUSTER=slack'