steps:
  - timeout: 600s
  - name: gcr.io/cloud-builders/docker
    args: [
      'build',
      '-f',
      './organization/Dockerfile',
      '-t',
      'gcr.io/slack-organization/slack-organization-dev:$BUILD_ID',
      '.'
    ]
  - name: gcr.io/cloud-builders/docker
    args: [
      'push',
      'gcr.io/slack-organization/slack-organization-dev:$BUILD_ID'
    ]
  - name: gcr.io/cloud-builders/kubectl
    args: [
      'set',
      'image',
      'deployment/organization-depl',
      'd3bug3r/slack-organization=gcr.io/slack-organization/slack-organization-dev:$BUILD_ID',
    ]
  - name: 'gcr.io/cloud-builders/kubectl'
    id: Deploy
    args: [
      'apply',
      '-f',
      'infra/k8s/organization-depl.yaml'
    ]
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
      - 'CLOUDSDK_CONTAINER_CLUSTER=slack'