steps:
  - name: gcr.io/cloud-builders/docker
    args: [
      'build',
      '-f',
      './user/Dockerfile.dev',
      '-t',
      'gcr.io/ticketing-dev-281211/slack-user-dev:$BUILD_ID',
      './user'
    ]
  - name: gcr.io/cloud-builders/docker
    args: [
      'push',
      'gcr.io/ticketing-dev-281211/slack-user-dev:$BUILD_ID'
    ]
  - name: gcr.io/cloud-builders/kubectl
    args: [
      'set',
      'image',
      'deployment/user-depl',
      'slack-user=gcr.io/ticketing-dev-281211/slack-user-dev:$BUILD_ID',
    ]
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
      - 'CLOUDSDK_CONTAINER_CLUSTER=slack'
  # - name: 'gcr.io/cloud-builders/kubectl'
  #   id: Deploy
  #   args: [
  #     'apply',
  #     '-f',
  #     'infra/k8s/user-depl.yaml'
  #   ]
  #   env:
  #     - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
  #     - 'CLOUDSDK_CONTAINER_CLUSTER=slack'