apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
      - http:
          paths:
            - path: /graphql
              backend:
                serviceName: api-gateway-srv
                servicePort: 3000
            - path: /api/users/?(.*)
              backend:
                serviceName: user-srv
                servicePort: 3000
            - path: /api/organization/?(.*)
              backend:
                serviceName: organization-srv
                servicePort: 3000
            - path: /api/channel/?(.*)
              backend:
                serviceName: channel-srv
                servicePort: 3000
            - path: /?(.*)
              backend:
                serviceName: client-srv
                servicePort: 3000
