steps:
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
    dir: 'client'
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build:prod']
    dir: 'client'
  - name: 'gcr.io/ticketing-dev-281211/firebase'
    args: [
      'deploy',
      '--project=ticketing-dev-281211',
      '--only=hosting:slack-prod'
    ]
    dir: 'client'