apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-depl
  namespace: production
spec:
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: slack-api-gateway-prod
          image: gcr.io/ticketing-dev-281211/slack-api-gateway-prod
          env:
            - name: ORGANIZATION_URI
              value: http://organization-srv:3000/api/organization/graphql
            - name: USER_URI
              value: http://user-srv:3000/api/users/graphql
            - name: CHANNEL_URI
              value: http://channel-srv:3000/api/channel/graphql
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway-srv
  namespace: production
spec:
  selector:
    app: api-gateway
  ports:
    - name: api-gateway
      protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: api-gateway-hpa
  namespace: production
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-gateway-depl
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
  - type: Resource
    resource:
      name: memory
      target:
        type: AverageValue
        averageValue: 18000Mi